### ISSUE TITLE
cellCellReport returns Error:public 

### ISSUE THREAD

**Issue by MJ-Yang** [rikenbit/scTensor#5] opened 2019-07-22 06:12 UTC
Hi,

I've run cellCellReport after cellCellDecomp, however it throws Error:public and the output directories figures , Ligand, Receptor etc are all empty. 
I'm not sure what is wrong. 

> cellCellReport(sce,reducedDimNames = "UMAP" ,thr=40, out.dir = wd)
snapshotDate(): 2018-10-24
Error: Public

btw, tutorial on 10X datasets would be very helpful ! 
Big Thanks,
MJ Yang

**Comment by kokitsuyuzaki** [comment] 2019-07-22 11:14
Hi, @MJ-Yang 

Thanks!
Please let me know if you have any requests for scTensor.

Is the version of scTensor is v-1.0.7?
This situation is very similar to issue3.
https://github.com/rikenbit/scTensor/issues/3

Your data is about Human?
Could you send me your source code and data, to reproduce the error in my environment?

Koki

**Comment by MJ-Yang** [comment] 2019-07-22 12:33
Yes I've updated version to 1.0.7 and my data is mouse data.

Also, one more question regarding the LRBase.Mmu.eg.db.

I've found some genes that are known as ligand but appears in GENEID_R

For example, ligand such as Vegfa (ENTREZID : 22339) pops up in list of receptors in the database. 

Thanks, 

MJ

**Comment by kokitsuyuzaki** [comment] 2019-07-23 04:03
Is the version of R v-3.5.0?
In my environment (R v-3.6.0), this error does not appear.

**Comment by kokitsuyuzaki** [comment] 2019-07-23 04:17
In LRBase, ligand and receptor are paired,
if these proteins have high PPI score (STRING),
and if subcellular localization is "secreted" (candidate ligand) and "plasma membrane" (candidate receptor).
https://www.bioconductor.org/packages/devel/bioc/vignettes/scTensor/inst/doc/scTensor.html

Actually, Vegfa of mouse can be regarded as a receptor,
because the protein is located in "plasma membrane".
https://www.uniprot.org/uniprot/Q00731

If you want to use more strict LR pair list,
You can use other databases such as IUPHAR, which is manually curated.
FANTOM5 merged the IUPHAR and the result of the prediction.

Using makeLRBasePackage function of LRBaseDbi package,
any LR databases can be used with scTensor.

see the vignette of scTensor
https://www.bioconductor.org/packages/devel/bioc/vignettes/scTensor/inst/doc/scTensor.html

Koki

**Comment by kokitsuyuzaki** [comment] 2019-07-23 05:19
Hi, 

I can now reproduce this error when the version of R specified as v-3.5.0.
I'll consider the another way to access to AnnotationHub.

**Comment by kokitsuyuzaki** [comment] 2019-07-29 14:06
Hi,

From v-1.0.8, this problem is resolved.
Please re-install and check it.

Koki

**Closed as completed by kokitsuyuzaki** 2019-07-29 14:06 UTC
